In [1]:
import pandas as pd
import numpy as np

In [2]:
esg_df = pd.read_csv("D:\\D Drive\\Woxsen\\Projects\\esg and finance\\sp500_esg_data_latest.csv")

In [3]:
esg_df.head()

,Symbol,Full Name,GICS Sector,GICS Sub-Industry,environmentScore,socialScore,governanceScore,totalEsg,highestControversy,ratingYear,ratingMonth,marketCap,beta,overallRisk
0,A,Agilent Technologies,Health Care,Life Sciences Tools & Services,1.14,6.23,3.93,11.31,1.0,2025.0,2.0,36033359872,1.111,7
1,AAPL,Apple Inc.,Information Technology,"Technology Hardware, Storage & Peripherals",0.55,7.31,8.50,16.36,3.0,2025.0,2.0,3575710482432,1.178,1
2,ABBV,AbbVie,Health Care,Biotechnology,1.78,15.71,8.48,25.97,2.0,2025.0,2.0,373336211456,0.598,7
3,ABNB,Airbnb,Consumer Discretionary,"Hotels, Resorts & Cruise Lines",1.30,13.81,8.28,23.39,2.0,2025.0,2.0,87596515328,1.108,10
4,ABT,Abbott Laboratories,Health Care,Health Care Equipment,1.81,13.77,6.05,21.62,3.0,2025.0,2.0,243186352128,0.693,6

In [4]:
esg_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 488 entries, 0 to 487
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Symbol              488 non-null    object
 1   Full Name           488 non-null    object
 2   GICS Sector         488 non-null    object
 3   GICS Sub-Industry   488 non-null    object
 4   environmentScore    488 non-null    float64
 5   socialScore         488 non-null    float64
 6   governanceScore     488 non-null    float64
 7   totalEsg            488 non-null    float64
 8   highestControversy  488 non-null    float64
 9   ratingYear          488 non-null    float64
 10  ratingMonth         488 non-null    float64
 11  marketCap           488 non-null    int64
 12  beta                488 non-null    float64
 13  overallRisk         488 non-null    int64
dtypes: float64(8), int64(2), object(4)
memory usage: 53.5+ KB

In [5]:
esg_df.isnull().sum()

Symbol                0
Full Name             0
GICS Sector           0
GICS Sub-Industry     0
environmentScore      0
socialScore           0
governanceScore       0
totalEsg              0
highestControversy    0
ratingYear            0
ratingMonth           0
marketCap             0
beta                  0
overallRisk           0
dtype: int64

In [6]:
import pandas as pd

# Load the Excel workbook
price_xls = pd.ExcelFile("D:\\D Drive\\Woxsen\\Projects\\esg and finance\\sp500_price_data1.xlsx")

# Dictionary to hold the long-format DataFrames for each sheet
long_dfs = {}

# Process each sheet in the workbook
for sheet in price_xls.sheet_names:
    # Read the current sheet into a DataFrame
    df = pd.read_excel(price_xls, sheet_name=sheet)
    
    # Convert to long format using "Date" as the identifier and the sheet name as the value column name
    price_data_long = df.melt(id_vars=["Date"], var_name="Symbol", value_name=sheet)
    
    # Save the long DataFrame in the dictionary
    long_dfs[sheet] = price_data_long

# Example: print the first few rows of the long-format DataFrame for the 'Close' sheet
print(long_dfs["Close"].head())

        Date Symbol       Close
0 2024-01-02      A  137.793884
1 2024-01-03      A  130.256210
2 2024-01-04      A  130.097305
3 2024-01-05      A  129.660324
4 2024-01-08      A  132.460907

In [7]:
long_dfs

{'Close':              Date Symbol       Close
 0      2024-01-02      A  137.793884
 1      2024-01-03      A  130.256210
 2      2024-01-04      A  130.097305
 3      2024-01-05      A  129.660324
 4      2024-01-08      A  132.460907
 ...           ...    ...         ...
 140839 2025-02-24    ZTS  165.309998
 140840 2025-02-25    ZTS  168.529999
 140841 2025-02-26    ZTS  164.990005
 140842 2025-02-27    ZTS  164.979996
 140843 2025-02-28    ZTS  167.240005

 [140844 rows x 3 columns],
 'High':              Date Symbol        High
 0      2024-01-02      A  139.621201
 1      2024-01-03      A  137.049074
 2      2024-01-04      A  130.593860
 3      2024-01-05      A  131.050686
 4      2024-01-08      A  132.649600
 ...           ...    ...         ...
 140839 2025-02-24    ZTS  165.570007
 140840 2025-02-25    ZTS  168.990005
 140841 2025-02-26    ZTS  169.000000
 140842 2025-02-27    ZTS  167.449997
 140843 2025-02-28    ZTS  167.619995

 [140844 rows x 3 columns],
 'Low':              Date Symbol         Low
 0      2024-01-02      A  136.959676
 1      2024-01-03      A  130.166834
 2      2024-01-04      A  129.292889
 3      2024-01-05      A  127.733690
 4      2024-01-08      A  128.915500
 ...           ...    ...         ...
 140839 2025-02-24    ZTS  160.820007
 140840 2025-02-25    ZTS  163.350006
 140841 2025-02-26    ZTS  164.880005
 140842 2025-02-27    ZTS  164.500000
 140843 2025-02-28    ZTS  163.889999

 [140844 rows x 3 columns],
 'Open':              Date Symbol        Open
 0      2024-01-02      A  137.237746
 1      2024-01-03      A  137.049074
 2      2024-01-04      A  129.650409
 3      2024-01-05      A  129.104185
 4      2024-01-08      A  129.243228
 ...           ...    ...         ...
 140839 2025-02-24    ZTS  162.080002
 140840 2025-02-25    ZTS  165.899994
 140841 2025-02-26    ZTS  168.210007
 140842 2025-02-27    ZTS  164.600006
 140843 2025-02-28    ZTS  165.889999

 [140844 rows x 3 columns],
 'Volume':              Date Symbol     Volume
 0      2024-01-02      A  1441600.0
 1      2024-01-03      A  2074500.0
 2      2024-01-04      A  2446600.0
 3      2024-01-05      A  1394000.0
 4      2024-01-08      A  1311400.0
 ...           ...    ...        ...
 140839 2025-02-24    ZTS  3698000.0
 140840 2025-02-25    ZTS  4003300.0
 140841 2025-02-26    ZTS  2609700.0
 140842 2025-02-27    ZTS  2253500.0
 140843 2025-02-28    ZTS  3333300.0

 [140844 rows x 3 columns]}

In [8]:
for sheet, df in long_dfs.items():
    null_count = df.isnull().sum()
    print(f"Null values in sheet '{sheet}':")
    print(null_count)
    print("-" * 50)

Null values in sheet 'Close':
Date        0
Symbol      0
Close     291
dtype: int64
--------------------------------------------------
Null values in sheet 'High':
Date        0
Symbol      0
High      291
dtype: int64
--------------------------------------------------
Null values in sheet 'Low':
Date        0
Symbol      0
Low       291
dtype: int64
--------------------------------------------------
Null values in sheet 'Open':
Date        0
Symbol      0
Open      291
dtype: int64
--------------------------------------------------
Null values in sheet 'Volume':
Date        0
Symbol      0
Volume    291
dtype: int64
--------------------------------------------------

In [9]:
#dropping null values in the sheets
for sheet, df in long_dfs.items():
    long_dfs[sheet] = df.dropna()

In [10]:
for sheet, df in long_dfs.items():
    null_count = df.isnull().sum()
    print(f"Null values in sheet '{sheet}':")
    print(null_count)
    print("-" * 50)

Null values in sheet 'Close':
Date      0
Symbol    0
Close     0
dtype: int64
--------------------------------------------------
Null values in sheet 'High':
Date      0
Symbol    0
High      0
dtype: int64
--------------------------------------------------
Null values in sheet 'Low':
Date      0
Symbol    0
Low       0
dtype: int64
--------------------------------------------------
Null values in sheet 'Open':
Date      0
Symbol    0
Open      0
dtype: int64
--------------------------------------------------
Null values in sheet 'Volume':
Date      0
Symbol    0
Volume    0
dtype: int64
--------------------------------------------------

In [11]:
esg_df.columns

Index(['Symbol', 'Full Name', 'GICS Sector', 'GICS Sub-Industry',
       'environmentScore', 'socialScore', 'governanceScore', 'totalEsg',
       'highestControversy', 'ratingYear', 'ratingMonth', 'marketCap', 'beta',
       'overallRisk'],
      dtype='object')

In [12]:
merged_prices = None

for sheet, df in long_dfs.items():
    if merged_prices is None:
        merged_prices = df
    else:
        # Merge on Date and Symbol so that each price type becomes its own column
        merged_prices = pd.merge(merged_prices, df, on=["Date", "Symbol"], how="outer")

# Now merge the combined price data with esg_df on "Symbol"
final_merged_data = pd.merge(merged_prices, esg_df, on="Symbol", how="inner")

# Check the result
print(final_merged_data.head())

        Date Symbol       Close        High         Low        Open  \
0 2024-01-02      A  137.793884  139.621201  136.959676  137.237746
1 2024-01-02   AAPL  184.532074  187.315366  182.792518  186.033057
2 2024-01-02   ABBV  152.743393  153.049216  147.916997  148.041231
3 2024-01-02   ABNB  134.479996  135.600006  133.339996  134.429993
4 2024-01-02    ABT  107.138481  108.260096  106.855639  106.855639

       Volume             Full Name             GICS Sector  \
0   1441600.0  Agilent Technologies             Health Care
1  82488700.0            Apple Inc.  Information Technology
2   8059900.0                AbbVie             Health Care
3   3485200.0                Airbnb  Consumer Discretionary
4   5058600.0   Abbott Laboratories             Health Care

                            GICS Sub-Industry  environmentScore  socialScore  \
0              Life Sciences Tools & Services              1.14         6.23
1  Technology Hardware, Storage & Peripherals              0.55         7.31
2                               Biotechnology              1.78        15.71
3              Hotels, Resorts & Cruise Lines              1.30        13.81
4                       Health Care Equipment              1.81        13.77

   governanceScore  totalEsg  highestControversy  ratingYear  ratingMonth  \
0             3.93     11.31                 1.0      2025.0          2.0
1             8.50     16.36                 3.0      2025.0          2.0
2             8.48     25.97                 2.0      2025.0          2.0
3             8.28     23.39                 2.0      2025.0          2.0
4             6.05     21.62                 3.0      2025.0          2.0

       marketCap   beta  overallRisk
0    36033359872  1.111            7
1  3575710482432  1.178            1
2   373336211456  0.598            7
3    87596515328  1.108           10
4   243186352128  0.693            6

In [13]:
final_merged_data

,Date,Symbol,Close,High,Low,Open,Volume,Full Name,GICS Sector,GICS Sub-Industry,environmentScore,socialScore,governanceScore,totalEsg,highestControversy,ratingYear,ratingMonth,marketCap,beta,overallRisk
0,2024-01-02,A,137.793884,139.621201,136.959676,137.237746,1441600.0,Agilent Technologies,Health Care,Life Sciences Tools & Services,1.14,6.23,3.93,11.31,1.0,2025.0,2.0,36033359872,1.111,7
1,2024-01-02,AAPL,184.532074,187.315366,182.792518,186.033057,82488700.0,Apple Inc.,Information Technology,"Technology Hardware, Storage & Peripherals",0.55,7.31,8.50,16.36,3.0,2025.0,2.0,3575710482432,1.178,1
2,2024-01-02,ABBV,152.743393,153.049216,147.916997,148.041231,8059900.0,AbbVie,Health Care,Biotechnology,1.78,15.71,8.48,25.97,2.0,2025.0,2.0,373336211456,0.598,7
3,2024-01-02,ABNB,134.479996,135.600006,133.339996,134.429993,3485200.0,Airbnb,Consumer Discretionary,"Hotels, Resorts & Cruise Lines",1.30,13.81,8.28,23.39,2.0,2025.0,2.0,87596515328,1.108,10
4,2024-01-02,ABT,107.138481,108.260096,106.855639,106.855639,5058600.0,Abbott Laboratories,Health Care,Health Care Equipment,1.81,13.77,6.05,21.62,3.0,2025.0,2.0,243186352128,0.693,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140548,2025-02-28,XYL,130.889999,131.160004,128.729996,129.669998,2510800.0,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,10.49,8.01,4.36,22.86,1.0,2025.0,2.0,31529400320,1.081,2
140549,2025-02-28,YUM,156.369995,156.559998,153.940002,154.169998,3003400.0,Yum! Brands,Consumer Discretionary,Restaurants,7.04,10.25,3.22,20.51,2.0,2025.0,2.0,43799478272,1.029,3
140550,2025-02-28,ZBH,104.320000,105.559998,102.419998,104.809998,2813600.0,Zimmer Biomet,Health Care,Health Care Equipment,4.89,13.99,7.31,26.19,2.0,2025.0,2.0,20977258496,1.039,2
140551,2025-02-28,ZBRA,315.049988,315.309998,307.160004,310.049988,611600.0,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,1.79,3.34,4.81,9.94,0.0,2025.0,2.0,15765193728,1.679,10
140552,2025-02-28,ZTS,167.240005,167.619995,163.889999,165.889999,3333300.0,Zoetis,Health Care,Pharmaceuticals,2.68,5.80,6.60,15.08,2.0,2025.0,2.0,76361965568,0.941,2

In [14]:
final_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140553 entries, 0 to 140552
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Date                140553 non-null  datetime64[ns]
 1   Symbol              140553 non-null  object
 2   Close               140553 non-null  float64
 3   High                140553 non-null  float64
 4   Low                 140553 non-null  float64
 5   Open                140553 non-null  float64
 6   Volume              140553 non-null  float64
 7   Full Name           140553 non-null  object
 8   GICS Sector         140553 non-null  object
 9   GICS Sub-Industry   140553 non-null  object
 10  environmentScore    140553 non-null  float64
 11  socialScore         140553 non-null  float64
 12  governanceScore     140553 non-null  float64
 13  totalEsg            140553 non-null  float64
 14  highestControversy  140553 non-null  float64
 15  ratingYear          140553 non-null  float64
 16  ratingMonth         140553 non-null  float64
 17  marketCap           140553 non-null  int64
 18  beta                140553 non-null  float64
 19  overallRisk         140553 non-null  int64
dtypes: datetime64[ns](1), float64(13), int64(2), object(4)
memory usage: 21.4+ MB

In [15]:
final_merged_data.to_csv('merged_data.csv')

In [16]:
final_merged_data.describe()

,Date,Close,High,Low,Open,Volume,environmentScore,socialScore,governanceScore,totalEsg,highestControversy,ratingYear,ratingMonth,marketCap,beta,overallRisk
count,140553,140553.000000,140553.000000,140553.000000,140553.000000,1.405530e+05,140553.000000,140553.000000,140553.00000,140553.000000,140553.000000,140553.000000,140553.000000,1.405530e+05,140553.000000,140553.000000
mean,2024-07-30 10:53:11.752577280,209.724142,211.958315,207.478229,209.766100,5.575437e+06,5.931366,9.100973,5.54528,20.577702,1.784679,2024.985507,2.062112,1.024711e+11,1.066770,5.451346
min,2024-01-02 00:00:00,6.710000,6.980000,6.640000,6.670000,8.800000e+03,0.000000,0.890000,2.04000,7.280000,0.000000,2023.000000,2.000000,4.436671e+09,0.012000,1.000000
25%,2024-04-16 00:00:00,66.051521,66.811114,65.300003,66.050003,1.018500e+06,1.890000,6.750000,4.02000,15.340000,1.000000,2025.000000,2.000000,1.959640e+10,0.776000,3.000000
50%,2024-07-31 00:00:00,120.873795,122.185677,119.500000,120.870653,2.076600e+06,4.300000,8.950000,4.97000,20.040000,2.000000,2025.000000,2.000000,3.661725e+10,1.063000,5.000000
75%,2024-11-12 00:00:00,223.731033,225.992398,221.462866,223.775302,4.690800e+06,9.210000,11.540000,6.56000,24.890000,2.000000,2025.000000,2.000000,8.077637e+10,1.295000,8.000000
max,2025-02-28 00:00:00,9924.400391,9964.769531,9794.000000,9914.169922,1.142269e+09,27.690000,22.180000,18.20000,43.660000,5.000000,2025.000000,11.000000,3.575710e+12,3.270000,10.000000
std,NaN,468.377348,473.477080,463.558339,468.521321,2.055294e+07,5.096977,3.600060,2.22837,6.665455,0.884194,0.163417,0.684248,2.998227e+11,0.433249,2.855975